version: '3.9'

services:
  backend:
    build: ./app
    command: bash -c "python manage.py migrate && python manage.py collectstatic  && gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./app/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
      - static:/app/static
      - media:/app/media
    env_file:
      - ./.env.db
volumes:
  pgdata:
  static:
  media:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static:ro
      - ./media:/app/media:ro
    ports:
      - 80:80
    depends_on:
      - backend 
